# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ModelParts',
                'verbose_name': 'Model Part',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_code', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('base_sales_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Models',
                'verbose_name': 'Model',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Images')),
            ],
            options={
                'db_table': 'Parts',
                'verbose_name': 'Part',
            },
        ),
        migrations.AddField(
            model_name='modelparts',
            name='models',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodel.Models'),
        ),
        migrations.AddField(
            model_name='modelparts',
            name='parts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodel.Parts'),
        ),
        migrations.AlterUniqueTogether(
            name='modelparts',
            unique_together=set([('parts', 'models')]),
        ),
    ]
