# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basemodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'Market',
                'verbose_name': 'Market',
            },
        ),
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'ModelCategory',
                'verbose_name': 'ModelCategory',
            },
        ),
        migrations.AddField(
            model_name='models',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='models',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basemodel.ModelCategory'),
        ),
        migrations.AddField(
            model_name='models',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basemodel.Market'),
        ),
    ]
