# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemodel', '0003_auto_20170504_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
