# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basemodel', '0004_auto_20170504_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'BaseModels',
                'verbose_name': 'BaseModels',
            },
        ),
        migrations.RemoveField(
            model_name='models',
            name='base_sales_code',
        ),
        migrations.AddField(
            model_name='models',
            name='base_models',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basemodel.BaseModels'),
        ),
    ]
