# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemodel', '0006_auto_20170519_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='description',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
