# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ThresholdHistory',
                'verbose_name': 'Threshold History',
            },
        ),
        migrations.CreateModel(
            name='ThresholdNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ThresholdNotifications',
                'verbose_name': 'Threshold Notification',
            },
        ),
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no_of_occurances', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=45)),
                ('reset_upon_notification', models.CharField(max_length=45)),
                ('inspection_point_defects', models.IntegerField()),
            ],
            options={
                'db_table': 'Thresholds',
                'verbose_name': 'Threshold',
            },
        ),
        migrations.AddField(
            model_name='thresholdnotifications',
            name='threshold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threshold.Thresholds'),
        ),
        migrations.AddField(
            model_name='thresholdhistory',
            name='threshold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threshold.Thresholds'),
        ),
    ]
