# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import inspection.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodel', '0001_initial'),
        ('checkpoints', '0001_initial'),
        ('reports', '__first__'),
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectClosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.FileField(blank=True, null=True, upload_to=inspection.models.update_filename_defectclosure)),
                ('image_2', models.CharField(max_length=45)),
                ('image_quadrant', models.IntegerField(blank=True, default=0, null=True)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('activity_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'DefectClosure',
                'verbose_name': 'Defect Closure',
            },
        ),
        migrations.CreateModel(
            name='InspectionDefects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.CharField(blank=True, max_length=300, null=True)),
                ('image_2', models.FileField(blank=True, null=True, upload_to=inspection.models.update_filename_inspectiondefects)),
                ('image_quadrant', models.IntegerField(blank=True, default=0, null=True)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('checkpoints', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoints.Checkpoints')),
                ('image_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Images')),
                ('partdefects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoints.PartDefects')),
            ],
            options={
                'db_table': 'InspectionDefects',
                'verbose_name': 'Inspection Defect',
            },
        ),
        migrations.CreateModel(
            name='VinDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('closed_time', models.DateTimeField(null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodel.Models')),
                ('stations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Stations')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Users')),
            ],
            options={
                'db_table': 'VinDetails',
                'verbose_name': 'Vin Detail',
            },
        ),
        migrations.AddField(
            model_name='inspectiondefects',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.VinDetails'),
        ),
        migrations.AddField(
            model_name='defectclosure',
            name='inspection_defects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionDefects'),
        ),
        migrations.AddField(
            model_name='defectclosure',
            name='repairs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkpoints.Repairs'),
        ),
        migrations.AlterUniqueTogether(
            name='vindetails',
            unique_together=set([('vin', 'stations')]),
        ),
        migrations.AlterUniqueTogether(
            name='inspectiondefects',
            unique_together=set([('vin', 'partdefects')]),
        ),
        migrations.AlterUniqueTogether(
            name='defectclosure',
            unique_together=set([('inspection_defects', 'repairs')]),
        ),
    ]
