# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defects_count', models.IntegerField(blank=True, default=0, null=True)),
                ('closure_count', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(default=False)),
                ('stations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Stations')),
                ('vin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.VinDetails')),
            ],
        ),
    ]
