# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_auto_20170417_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(default='NOT OK', max_length=50),
        ),
    ]
