# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170426_1555'),
        ('inspection', '0005_vinstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinstatus',
            options={'verbose_name': 'VinStatu'},
        ),
        migrations.AddField(
            model_name='defectclosure',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Users'),
        ),
        migrations.AddField(
            model_name='inspectiondefects',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Users'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(default='RFT NOT OK', max_length=50),
        ),
    ]
