# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_auto_20170426_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectsPerUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_defects', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_tracktores', models.IntegerField(blank=True, default=0, null=True)),
                ('dpu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'VinStatus',
                'verbose_name': 'VinStatu',
            },
        ),
    ]
