# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_defectsperunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defectsperunit',
            options={'verbose_name': 'DefectsPerUnit'},
        ),
        migrations.AlterModelTable(
            name='defectsperunit',
            table='DefectsPerUnit',
        ),
    ]
