# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_auto_20170426_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=300, null=True)),
                ('tot_defects', models.IntegerField(blank=True, default=0, null=True)),
                ('tot_closure', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'VinStatus',
                'verbose_name': 'VinStatus',
            },
        ),
    ]
