# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_auto_20170426_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinstatus',
            old_name='latest_modified_date',
            new_name='last_modified_date',
        ),
    ]
