# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_auto_20170426_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectsperunit',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
