# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0013_verification_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=300, null=True)),
                ('final_status', models.CharField(blank=True, max_length=300, null=True)),
                ('overall_status', models.CharField(blank=True, max_length=300, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'FinalRFT',
                'verbose_name': 'FinalRFT',
            },
        ),
        migrations.AlterField(
            model_name='defectsperunit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
