# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0014_auto_20170502_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectsperunit',
            old_name='no_of_tracktores',
            new_name='no_of_tractors',
        ),
    ]
