# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0015_auto_20170503_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectclosure',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='defectsperunit',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectiondefects',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vindetails',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
