# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20170523_1233'),
        ('inspection', '0016_auto_20170504_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='vindetails',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.Shifts'),
            preserve_default=False,
        ),
    ]
