# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0017_vindetails_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='vindetails',
            name='vin_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
