# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20170523_1233'),
        ('inspection', '0018_vindetails_vin_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vindetails',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.Plants'),
            preserve_default=False,
        ),
    ]
