# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodel', '0001_initial'),
        ('reports', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Cells',
                'verbose_name': 'Cell',
            },
        ),
        migrations.CreateModel(
            name='DefectCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'DefectCategories',
                'verbose_name': 'DefectCategorie',
            },
        ),
        migrations.CreateModel(
            name='ModelStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodel.Models')),
            ],
            options={
                'db_table': 'ModelStations',
                'verbose_name': 'Model Station',
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Plants',
                'verbose_name': 'Plant',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Roles',
                'verbose_name': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Plants')),
            ],
            options={
                'db_table': 'Shifts',
                'verbose_name': 'Shift',
            },
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'SkillLevel',
                'verbose_name': 'SkillLevel',
            },
        ),
        migrations.CreateModel(
            name='SourceGates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'SourceGate',
                'verbose_name': 'SourceGate',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Images')),
            ],
            options={
                'db_table': 'Stages',
                'verbose_name': 'Stage',
            },
        ),
        migrations.CreateModel(
            name='StageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Shifts')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.SkillLevel')),
                ('stages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Stages')),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('cells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Cells')),
            ],
            options={
                'db_table': 'Stations',
                'verbose_name': 'Station',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Stations')),
            ],
            options={
                'db_table': 'UserLog',
                'verbose_name': 'UserLog',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('email_id', models.CharField(max_length=200, null=True)),
                ('key', models.CharField(editable=False, max_length=40, null=True, unique=True)),
                ('key_expiry_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_updated', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=300, null=True)),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Roles')),
            ],
            options={
                'db_table': 'Users',
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_skilled', models.BooleanField(default=True)),
                ('stages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Stages')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Users')),
                ('user_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.UserLog')),
            ],
            options={
                'db_table': 'VerificationLog',
                'verbose_name': 'VerificationLog',
            },
        ),
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Users'),
        ),
        migrations.AddField(
            model_name='stageuser',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Users'),
        ),
        migrations.AddField(
            model_name='stages',
            name='stations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Stations'),
        ),
        migrations.AddField(
            model_name='stages',
            name='users',
            field=models.ManyToManyField(related_name='stage_users', through='organization.StageUser', to='organization.Users'),
        ),
        migrations.AddField(
            model_name='modelstations',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Stations'),
        ),
        migrations.AddField(
            model_name='cells',
            name='plants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Plants'),
        ),
        migrations.AlterUniqueTogether(
            name='modelstations',
            unique_together=set([('model', 'station')]),
        ),
    ]
