# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='p@ssw0rd', max_length=100),
        ),
    ]
