# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170504_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='plants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.Plants'),
            preserve_default=False,
        ),
    ]
