# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_users_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstations',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelstations',
            name='is_rolldown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelstations',
            name='station_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
